set(EXTENSIONS_DIR ${CMAKE_CURRENT_LIST_DIR}/superbuild-extensions)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_joystick_plugin.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_residual_estimation.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_mujoco.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/rl_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/trajectory/TrajectoryCollection.cmake)
#include(${CMAKE_CURRENT_LIST_DIR}/controllers/HumanRetargetingRLController.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/sandbox_humanoid_controller.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/robots/Kinova.cmake)
#include(${CMAKE_CURRENT_LIST_DIR}/robots/h1.cmake)
#include(${CMAKE_CURRENT_LIST_DIR}/controllers/BaseLineWalkingController.cmake)
#include(${CMAKE_CURRENT_LIST_DIR}/controllers/HumanRetargetingController.cmake)
#include(${CMAKE_CURRENT_LIST_DIR}/gui/mc_rtc-magnum.cmake)
